export const DATA_MODELS_RESPONSE = {
  message: "success",
  data: {
    detail_info_fields: {
      email: { display_name: "Work Email", is_checked: true },
      doj: { display_name: "Date of Joining", is_checked: false },
      employmentType: { display_name: "Employment Type", is_checked: false },
      gender: { display_name: "Gender", is_checked: false },
      dob: { display_name: "Date of Birth", is_checked: true },
      pan: { display_name: "PAN", is_checked: false },
      personalEmail: { display_name: "Personal Email", is_checked: true },
      fatherName: { display_name: "Father's Name", is_checked: false },
      bloodGroup: { display_name: "Blood Group", is_checked: true },
      designation: { display_name: "Designation", is_checked: false },
      department: { display_name: "Department", is_checked: false },
      mobileNumber: { display_name: "Mobile Number", is_checked: false },
      manager: { display_name: "Manager", is_checked: true },
      maritalStatus: { display_name: "Marital Status", is_checked: false },
      nationality: { display_name: "Nationality", is_checked: false },
      aadhar: { display_name: "Aadhaar", is_checked: false },
      uan: { display_name: "UAN", is_checked: false },
      terminationDate: { display_name: "Termination Date", is_checked: false },
      grade: { display_name: "Grade", is_checked: false },
      groupName: { display_name: "Group Name", is_checked: false },
      costCenter: { display_name: "Cost Center", is_checked: false },
      managerEmail: { display_name: "Manager Email", is_checked: false },
      managerEmail2: { display_name: "Manager Email Level 2", is_checked: false },
      managerEmail3: { display_name: "Manager Email Level 3", is_checked: false },
      managerEmail4: { display_name: "Manager Email Level 4", is_checked: false },
      managerEmail5: { display_name: "Manager Email Level 5", is_checked: false },
      companyName: { display_name: "Company Name", is_checked: false },
      countryCode: { display_name: "Country Code", is_checked: false },
      currentAddress: { display_name: "Current Address", is_checked: false },
      permanentAddress: { display_name: "Permanent Address", is_checked: false },
      jobLocation: { display_name: "Job Location", is_checked: false },
      employeeMetadata_marriageDate: { display_name: "Marriage Date", is_checked: false },
    },
    bank_details_fields: {
      bankDetails_bankName: { display_name: "Bank Name", is_checked: true },
      bankDetails_ifscCode: { display_name: "IFSC Code", is_checked: true },
      bankDetails_accountNumber: { display_name: "Account Number", is_checked: true },
    },
    dependent_details_fields: {
      dependentDetails_name: { display_name: "Dependent's Name", is_checked: true },
      dependentDetails_relation: { display_name: "Dependent's Relation", is_checked: true },
      dependentDetails_dob: { display_name: "Dependent's Date of Birth", is_checked: true },
      dependentDetails_mobileNumber: { display_name: "Dependent's Mobile Number", is_checked: true },
      dependentDetails_email: { display_name: "Dependent's Email", is_checked: true },
      dependentDetails_gender: { display_name: "Dependent's Gender", is_checked: true },
      dependentDetails_profession: { display_name: "Dependent's Profession", is_checked: true },
    },
    salary_details_fields: {
      basic: { display_name: "Basic", is_checked: true },
      hra: { display_name: "House Rent Allowance", is_checked: true },
      specialAllowance: { display_name: "Special Allowance", is_checked: true },
      medicalAllowance: { display_name: "Medical Allowance", is_checked: true },
      dearnessAllowance: { display_name: "Dearness Allowance", is_checked: true },
      otherAllowance: { display_name: "Other Allowance", is_checked: true },
      travelAllowance: { display_name: "Travel Allowance", is_checked: true },
      totalEarnings: { display_name: "Total Earnings", is_checked: true },
      tds: { display_name: "Income Tax", is_checked: true },
      mediclaimDeduction: { display_name: "Mediclaim Deduction", is_checked: true },
      pfDeductions: { display_name: "PF", is_checked: true },
      otherDeductions: { display_name: "Other Deductions", is_checked: true },
      totalDeductions: { display_name: "Total Deductions", is_checked: true },
      loan: { display_name: "Loan", is_checked: true },
      esic: { display_name: "ESIC", is_checked: true },
      labourWelfFund: { display_name: "Labour Fund", is_checked: true },
      professionalTax: { display_name: "ProfessionalTax", is_checked: true },
      groupTermInsuranceDeductions: { display_name: "Group Term Insurance Deductions", is_checked: true },
      gratuity: { display_name: "Gratuity", is_checked: true },
      early_wage_deduction: { display_name: "Early Wage Deduction", is_checked: true },
      netPay: { display_name: "Net Pay", is_checked: true },
      taxRegime: { display_name: "Tax Regime", is_checked: true },
      nps: { display_name: "NPS", is_checked: true },
    },
    ctc_details_fields: {
      ctc_basic: { display_name: "Basic", is_checked: true },
      ctc_hra: { display_name: "House Rent Allowance", is_checked: true },
      ctc_specialAllowance: { display_name: "Special Allowance", is_checked: true },
      ctc_medicalAllowance: { display_name: "Medical Allowance", is_checked: true },
      ctc_dearnessAllowance: { display_name: "Dearness Allowance", is_checked: true },
      ctc_flexiBasketAllowance: { display_name: "Flexi Basket Allowance", is_checked: true },
      ctc_travelAllowance: { display_name: "Travel Allowance", is_checked: true },
      ctc_otherAllowance: { display_name: "Other Allowance", is_checked: true },
      ctc_gratuity: { display_name: "Gratuity", is_checked: true },
      ctc_grossPay: { display_name: "Gross Pay", is_checked: true },
      ctc_fixedPay: { display_name: "Fixed Pay", is_checked: true },
      ctc_deductions_pf: { display_name: "PF Deductions", is_checked: true },
      ctc_deductions_esi: { display_name: "ESI", is_checked: true },
      ctc_deductions_misc: { display_name: "Miscellaneous Deduction", is_checked: true },
      ctc_deductions_labourWelfareFund: { display_name: "Labour Welfare Fund", is_checked: true },
      ctc_deductions_professionalTax: { display_name: "Professional Tax", is_checked: true },
      ctc_deductions_nps: { display_name: "NPS", is_checked: true },
      ctc_bonus_joining: { display_name: "Joining Bonus", is_checked: true },
      ctc_bonus_misc: { display_name: "Miscellaneous Bonus", is_checked: true },
      ctc_bonus_performance: { display_name: "Performance Bonus", is_checked: true },
      ctc_bonus_referral: { display_name: "Referal Bonus", is_checked: true },
      ctc_bonus_relocation: { display_name: "Relocation Bonus", is_checked: true },
      ctc_bonus_retention: { display_name: "Retetion Bonus", is_checked: true },
      ctc_taxRegime: { display_name: "Tax Regime", is_checked: true },
      ctc_raw: { display_name: "Raw", is_checked: true },
    },
    salary_monthly_details_fields: {
      monthly_basic: { display_name: "Basic", is_checked: true },
      monthly_dearnessAllowance: { display_name: "Dearness Allowance", is_checked: true },
      monthly_hra: { display_name: "House Rent Allowance", is_checked: true },
      monthly_medicalAllowance: { display_name: "Medical Allowance", is_checked: true },
      monthly_travelAllowance: { display_name: "Travel Allowance", is_checked: true },
      monthly_specialAllowance: { display_name: "Special Allowance", is_checked: true },
      monthly_flexiBasketAllowance: { display_name: "Flexi Basket Allowance", is_checked: true },
      monthly_gratuity: { display_name: "Gratuity", is_checked: true },
      monthly_otherAllowance: { display_name: "Other Allowance", is_checked: true },
      monthly_deductions_pf: { display_name: "PF Deductions", is_checked: true },
      monthly_deductions_esi: { display_name: "ESI Deductions", is_checked: true },
      monthly_deductions_professionalTax: { display_name: "Professional Tax Deductions", is_checked: true },
      monthly_deductions_labourWelfareFund: { display_name: "Labour Welfare Fund Deductions", is_checked: true },
      monthly_deductions_tds: { display_name: "TDS Deductions", is_checked: true },
      monthly_deductions_medicalClaimDeduction: { display_name: "Medical Claim Deductions", is_checked: true },
      monthly_deductions_groupTermInsuranceDeductions: { display_name: "Group Term Insurance Deductions", is_checked: true },
      monthly_deductions_earlyWageDeduction: { display_name: "Early Wage Deduction", is_checked: true },
      monthly_deductions_misc: { display_name: "Miscellaneous Deductions", is_checked: true },
      monthly_deductions_nps: { display_name: "NPS Deductions", is_checked: true },
      monthly_bonus_joining: { display_name: "Joining Bonus", is_checked: true },
      monthly_bonus_referral: { display_name: "Referral Bonus", is_checked: true },
      monthly_bonus_retention: { display_name: "Retention Bonus", is_checked: true },
      monthly_bonus_performance: { display_name: "Performance Bonus", is_checked: true },
      monthly_bonus_relocation: { display_name: "Relocation Bonus", is_checked: true },
      monthly_bonus_misc: { display_name: "Miscellaneous Bonus", is_checked: true },
      monthly_grossPay: { display_name: "Gross Pay", is_checked: true },
      monthly_fixedPay: { display_name: "Fixed Pay", is_checked: true },
      monthly_taxRegime: { display_name: "Tax Regime", is_checked: true },
      monthly_reimbursements: { display_name: "Reimbursements", is_checked: true },
      monthly_raw: { display_name: "Raw", is_checked: true },
    },
    basic_info_fields: {
      name: { category_key: "detail_info_fields", display_name: "Name", is_checked: true },
      employeeId: { category_key: "detail_info_fields", display_name: "Employee ID", is_checked: true },
      status: { category_key: "detail_info_fields", display_name: "Employment Status", is_checked: true },
    },
    configuration: {
      salary_flag: true,
      monthly_flag: true,
    },
  },
} as const;

export type DataModelCategoryKey =
  | "detail_info_fields"
  | "bank_details_fields"
  | "dependent_details_fields"
  | "salary_details_fields"
  | "ctc_details_fields"
  | "salary_monthly_details_fields"
  | "basic_info_fields";
